[package]
name = "literature_location_checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.17"
futures = "*"
tokio = { version = "*", features = ["full"] }
mockito = "0.26.0"